services:
  fpm:
    container_name: planocontratacao-fpm
    image: $CI_REGISTRY_IMAGE:php-fpm-${IMAGE_TAG:-latest}
    restart: unless-stopped
    env_file:
      - /opt/projetos/planocontratacao/.env
      - /opt/projetos/planocontratacao/.env.dev
    networks:
      - traefik-planocontratacao

  nginx:
    container_name: planocontratacao-nginx
    image: $CI_REGISTRY_IMAGE:nginx-${IMAGE_TAG:-latest}
    restart: unless-stopped
    networks:
      - traefik-planocontratacao
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.d-planocontratacao-http.rule=Host(`d-planocontratacao.tce.mt.gov.br`)"
      - "traefik.http.routers.d-planocontratacao-http.entrypoints=http"
      - "traefik.http.routers.d-planocontratacao-http.middlewares=redirect-to-https"

      - "traefik.http.routers.d-planocontratacao-https.rule=Host(`d-planocontratacao.tce.mt.gov.br`)"
      - "traefik.http.routers.d-planocontratacao-https.entrypoints=https"
      - "traefik.http.routers.d-planocontratacao-https.tls=true"

      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"
    depends_on:
      fpm:
        condition: service_started

networks:
  traefik-planocontratacao:
    external: true
