FROM php:8.3-fpm

# Add user for laravel application
RUN useradd -u 1000 -ms /bin/bash -g www-data www

#Install dependencies
RUN apt-get update
RUN apt-get install -y software-properties-common build-essential ca-certificates libpng-dev libjpeg62-turbo-dev libfreetype6-dev locales zip jpegoptim optipng pngquant gifsicle unzip git curl lua-zlib-dev libmemcached-dev libbz2-dev alien libaio1 wget

#Repositorio
ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/

# Install php extensions
RUN chmod +x /usr/local/bin/install-php-extensions
RUN install-php-extensions zip
RUN install-php-extensions exif
RUN install-php-extensions pcntl
RUN install-php-extensions gd
RUN install-php-extensions memcached
RUN install-php-extensions bz2
RUN install-php-extensions xdebug
RUN install-php-extensions readline
RUN install-php-extensions ldap
RUN install-php-extensions oci8
RUN install-php-extensions pdo_oci
RUN install-php-extensions sqlite3
RUN install-php-extensions imagick
RUN install-php-extensions soap
RUN install-php-extensions bcmath
RUN install-php-extensions redis
RUN install-php-extensions memcached
RUN install-php-extensions pcov
RUN install-php-extensions curl
RUN install-php-extensions imap
RUN install-php-extensions xml

COPY --chown=www:www-data .docker/php-fpm/php.ini /usr/local/etc/php/php.ini
COPY --chown=www:www-data .docker/php-fpm/www.conf /usr/local/etc/php-fpm.d/www.conf

WORKDIR /var/www/html

EXPOSE 9000
